name: Shell Commands

on: [push, pull_request]

jobs:
  run-shell-commands:
    runs-on: ubuntu-20.04
    steps:
      - name: echo a string
        run: echo "Hello Word from GitHub Actions"
      - name: multiline script
        run: |
          node -v
          npm -v
